# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jonne/Code/m8c

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jonne/Code/m8c

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jonne/Code/m8c/CMakeFiles /home/jonne/Code/m8c//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jonne/Code/m8c/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named m8c

# Build rule for target.
m8c: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 m8c
.PHONY : m8c

# fast build rule for target.
m8c/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/m8c.dir/build.make CMakeFiles/m8c.dir/build
.PHONY : m8c/fast

audio.o: audio.c.o
.PHONY : audio.o

# target to build an object file
audio.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/m8c.dir/build.make CMakeFiles/m8c.dir/audio.c.o
.PHONY : audio.c.o

audio.i: audio.c.i
.PHONY : audio.i

# target to preprocess a source file
audio.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/m8c.dir/build.make CMakeFiles/m8c.dir/audio.c.i
.PHONY : audio.c.i

audio.s: audio.c.s
.PHONY : audio.s

# target to generate assembly for a file
audio.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/m8c.dir/build.make CMakeFiles/m8c.dir/audio.c.s
.PHONY : audio.c.s

command.o: command.c.o
.PHONY : command.o

# target to build an object file
command.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/m8c.dir/build.make CMakeFiles/m8c.dir/command.c.o
.PHONY : command.c.o

command.i: command.c.i
.PHONY : command.i

# target to preprocess a source file
command.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/m8c.dir/build.make CMakeFiles/m8c.dir/command.c.i
.PHONY : command.c.i

command.s: command.c.s
.PHONY : command.s

# target to generate assembly for a file
command.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/m8c.dir/build.make CMakeFiles/m8c.dir/command.c.s
.PHONY : command.c.s

config.o: config.c.o
.PHONY : config.o

# target to build an object file
config.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/m8c.dir/build.make CMakeFiles/m8c.dir/config.c.o
.PHONY : config.c.o

config.i: config.c.i
.PHONY : config.i

# target to preprocess a source file
config.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/m8c.dir/build.make CMakeFiles/m8c.dir/config.c.i
.PHONY : config.c.i

config.s: config.c.s
.PHONY : config.s

# target to generate assembly for a file
config.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/m8c.dir/build.make CMakeFiles/m8c.dir/config.c.s
.PHONY : config.c.s

fx_cube.o: fx_cube.c.o
.PHONY : fx_cube.o

# target to build an object file
fx_cube.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/m8c.dir/build.make CMakeFiles/m8c.dir/fx_cube.c.o
.PHONY : fx_cube.c.o

fx_cube.i: fx_cube.c.i
.PHONY : fx_cube.i

# target to preprocess a source file
fx_cube.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/m8c.dir/build.make CMakeFiles/m8c.dir/fx_cube.c.i
.PHONY : fx_cube.c.i

fx_cube.s: fx_cube.c.s
.PHONY : fx_cube.s

# target to generate assembly for a file
fx_cube.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/m8c.dir/build.make CMakeFiles/m8c.dir/fx_cube.c.s
.PHONY : fx_cube.c.s

ini.o: ini.c.o
.PHONY : ini.o

# target to build an object file
ini.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/m8c.dir/build.make CMakeFiles/m8c.dir/ini.c.o
.PHONY : ini.c.o

ini.i: ini.c.i
.PHONY : ini.i

# target to preprocess a source file
ini.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/m8c.dir/build.make CMakeFiles/m8c.dir/ini.c.i
.PHONY : ini.c.i

ini.s: ini.c.s
.PHONY : ini.s

# target to generate assembly for a file
ini.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/m8c.dir/build.make CMakeFiles/m8c.dir/ini.c.s
.PHONY : ini.c.s

inprint2.o: inprint2.c.o
.PHONY : inprint2.o

# target to build an object file
inprint2.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/m8c.dir/build.make CMakeFiles/m8c.dir/inprint2.c.o
.PHONY : inprint2.c.o

inprint2.i: inprint2.c.i
.PHONY : inprint2.i

# target to preprocess a source file
inprint2.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/m8c.dir/build.make CMakeFiles/m8c.dir/inprint2.c.i
.PHONY : inprint2.c.i

inprint2.s: inprint2.c.s
.PHONY : inprint2.s

# target to generate assembly for a file
inprint2.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/m8c.dir/build.make CMakeFiles/m8c.dir/inprint2.c.s
.PHONY : inprint2.c.s

input.o: input.c.o
.PHONY : input.o

# target to build an object file
input.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/m8c.dir/build.make CMakeFiles/m8c.dir/input.c.o
.PHONY : input.c.o

input.i: input.c.i
.PHONY : input.i

# target to preprocess a source file
input.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/m8c.dir/build.make CMakeFiles/m8c.dir/input.c.i
.PHONY : input.c.i

input.s: input.c.s
.PHONY : input.s

# target to generate assembly for a file
input.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/m8c.dir/build.make CMakeFiles/m8c.dir/input.c.s
.PHONY : input.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/m8c.dir/build.make CMakeFiles/m8c.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/m8c.dir/build.make CMakeFiles/m8c.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/m8c.dir/build.make CMakeFiles/m8c.dir/main.c.s
.PHONY : main.c.s

render.o: render.c.o
.PHONY : render.o

# target to build an object file
render.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/m8c.dir/build.make CMakeFiles/m8c.dir/render.c.o
.PHONY : render.c.o

render.i: render.c.i
.PHONY : render.i

# target to preprocess a source file
render.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/m8c.dir/build.make CMakeFiles/m8c.dir/render.c.i
.PHONY : render.c.i

render.s: render.c.s
.PHONY : render.s

# target to generate assembly for a file
render.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/m8c.dir/build.make CMakeFiles/m8c.dir/render.c.s
.PHONY : render.c.s

ringbuffer.o: ringbuffer.c.o
.PHONY : ringbuffer.o

# target to build an object file
ringbuffer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/m8c.dir/build.make CMakeFiles/m8c.dir/ringbuffer.c.o
.PHONY : ringbuffer.c.o

ringbuffer.i: ringbuffer.c.i
.PHONY : ringbuffer.i

# target to preprocess a source file
ringbuffer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/m8c.dir/build.make CMakeFiles/m8c.dir/ringbuffer.c.i
.PHONY : ringbuffer.c.i

ringbuffer.s: ringbuffer.c.s
.PHONY : ringbuffer.s

# target to generate assembly for a file
ringbuffer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/m8c.dir/build.make CMakeFiles/m8c.dir/ringbuffer.c.s
.PHONY : ringbuffer.c.s

serial.o: serial.c.o
.PHONY : serial.o

# target to build an object file
serial.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/m8c.dir/build.make CMakeFiles/m8c.dir/serial.c.o
.PHONY : serial.c.o

serial.i: serial.c.i
.PHONY : serial.i

# target to preprocess a source file
serial.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/m8c.dir/build.make CMakeFiles/m8c.dir/serial.c.i
.PHONY : serial.c.i

serial.s: serial.c.s
.PHONY : serial.s

# target to generate assembly for a file
serial.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/m8c.dir/build.make CMakeFiles/m8c.dir/serial.c.s
.PHONY : serial.c.s

slip.o: slip.c.o
.PHONY : slip.o

# target to build an object file
slip.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/m8c.dir/build.make CMakeFiles/m8c.dir/slip.c.o
.PHONY : slip.c.o

slip.i: slip.c.i
.PHONY : slip.i

# target to preprocess a source file
slip.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/m8c.dir/build.make CMakeFiles/m8c.dir/slip.c.i
.PHONY : slip.c.i

slip.s: slip.c.s
.PHONY : slip.s

# target to generate assembly for a file
slip.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/m8c.dir/build.make CMakeFiles/m8c.dir/slip.c.s
.PHONY : slip.c.s

usb.o: usb.c.o
.PHONY : usb.o

# target to build an object file
usb.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/m8c.dir/build.make CMakeFiles/m8c.dir/usb.c.o
.PHONY : usb.c.o

usb.i: usb.c.i
.PHONY : usb.i

# target to preprocess a source file
usb.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/m8c.dir/build.make CMakeFiles/m8c.dir/usb.c.i
.PHONY : usb.c.i

usb.s: usb.c.s
.PHONY : usb.s

# target to generate assembly for a file
usb.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/m8c.dir/build.make CMakeFiles/m8c.dir/usb.c.s
.PHONY : usb.c.s

usb_audio.o: usb_audio.c.o
.PHONY : usb_audio.o

# target to build an object file
usb_audio.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/m8c.dir/build.make CMakeFiles/m8c.dir/usb_audio.c.o
.PHONY : usb_audio.c.o

usb_audio.i: usb_audio.c.i
.PHONY : usb_audio.i

# target to preprocess a source file
usb_audio.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/m8c.dir/build.make CMakeFiles/m8c.dir/usb_audio.c.i
.PHONY : usb_audio.c.i

usb_audio.s: usb_audio.c.s
.PHONY : usb_audio.s

# target to generate assembly for a file
usb_audio.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/m8c.dir/build.make CMakeFiles/m8c.dir/usb_audio.c.s
.PHONY : usb_audio.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... m8c"
	@echo "... audio.o"
	@echo "... audio.i"
	@echo "... audio.s"
	@echo "... command.o"
	@echo "... command.i"
	@echo "... command.s"
	@echo "... config.o"
	@echo "... config.i"
	@echo "... config.s"
	@echo "... fx_cube.o"
	@echo "... fx_cube.i"
	@echo "... fx_cube.s"
	@echo "... ini.o"
	@echo "... ini.i"
	@echo "... ini.s"
	@echo "... inprint2.o"
	@echo "... inprint2.i"
	@echo "... inprint2.s"
	@echo "... input.o"
	@echo "... input.i"
	@echo "... input.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... render.o"
	@echo "... render.i"
	@echo "... render.s"
	@echo "... ringbuffer.o"
	@echo "... ringbuffer.i"
	@echo "... ringbuffer.s"
	@echo "... serial.o"
	@echo "... serial.i"
	@echo "... serial.s"
	@echo "... slip.o"
	@echo "... slip.i"
	@echo "... slip.s"
	@echo "... usb.o"
	@echo "... usb.i"
	@echo "... usb.s"
	@echo "... usb_audio.o"
	@echo "... usb_audio.i"
	@echo "... usb_audio.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

